### ISSUE TITLE
Add a revise.autoSquash config 

### ISSUE THREAD

**Issue by mystor** [mystor/git-revise#10]
This would be similar to the [rebase.autoSquash] config variable for `git rebase -i`. It should only have an effect if the `-i` flag is passed to `git revise`.

The condition for this if check will need to be expanded to consider `git config`: https://github.com/mystor/git-revise/blob/9f10441a9cfd989c562fc740dbf47b4edaebc284/gitrevise/tui.py#L95-L96

[rebase.autoSquash]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-rebaseautoSquash

**Comment by lilyball** [comment]
FWIW `git-rebase` also supports `--no-autosquash` to override the `rebase.autoSquash` config flag. Personally I've never had a reason to disable autosquashing, but if it's not too much trouble it might be nice to support `--no-autosquash` here to override the proposed `revise.autoSquash` config flag.

**Comment by gerboengels** [comment]
Why not use the existing `rebase.autoSquash` and introduce a new one? I imagine people who already have `rebase.autoSquash` set will be expecting the autosquash behaviour.

Or maybe some hybrid form: look for `rebase.autoSquash == true` _or_ `revise.autoSquash == true`, except when `revise.autoSquash` is explicitly set to `false`?

**Comment by alerque** [comment]
@gerboengels The argument against that is that it's both surprising and difficult to discover. The reason I say it's surprising is it's not the way any other git options work. For example I have `transfer.fsckObjects = true` in my config, but that _only_ applies to one specific scenario. In order to have it across the board I have to set `fetch.fsckObjects` and `receive.fsckObjects` as well. The same is true for at least half a dozen other options in my config. There is no inheritance or cross-pollination between options like you describe in the base git config even though there would be plenty of room form one. As such a child tool like this that comes along and does something different would be surprising (in a bad way).

**Comment by lilyball** [comment]
@alerque There is actually some cross-pollination. The most obvious example is all of the various `color.*` options (e.g. `color.branch`), if unset, use the value from `color.ui`.

In fact, your very example does cross-pollinate. According to the documentation, if `fetch.fsckObjects` is unset, the value of `transfer.fsckObjects` is used instead.

**Comment by alerque** [comment]
@lilyball I stand corrected. In that case I guess this kind of inheritance could be considered. The logic should be slightly different than @gerboengels suggested however, it shouldn't matter what the key is set to if it is set explicitly at all that should override any inherited value.

**Comment by gerboengels** [comment]
Thanks for your replies.

Why I posed the question was because my personal intuition was use `rebase.autoSquash`. I already tried to implement that, only to find out about this thread later, which proposes `revise.autoSquash`.
My mental model of `git revise -i` is that it is `git rebase -i` but faster (both in execution and not having to recompile afterwards) albeit with some limitations (no 'edits' along the way). Within that mental model, I expect autosquashing to behave similar between rebase and revise, out of the box.

Are there use cases where `rebase.autoSquash` is set, but one doesn't want that by default for `git revise -i`? Or vice versa, where you do not want `git rebase -i` to autosquash by default, but do want that for `git revise -i`?
If those are clear use cases, it must be a separate option.
As said, in my mental model I do not expect the behaviour to differ, but I fully understand that my metal model is _not_ the actual model, and `git revise` _is_ a different command than `git rebase`. And in that reasoning, `git revise` shoudn't consider `rebase.*` options.

I'm not really in favour of my own suggested hybrid form (considering both `rebase.autoSquash` and `revise.autoSquash`), because it makes it too complex.

I'll try to get a PR out, and I'm happy to support whatever configuration option seems most fit, but for that I do need some kind of conclusion :)

**Comment by lilyball** [comment]
I think it makes sense to add a `revise.autoSquash`, and if it's not set then to fall back to `rebase.autoSquash`. That matches precedent established by other Git config values.

**Comment by gerboengels** [comment]
@lilyball So if I understand you correctly, it should follow these rules (which is what I meant with the hybrid form)

if `--autosquash` argument present: true
if `--no-autosquash` argument present: false
if `git config --get --bool revise.autoSquash` == `true`: true
if `git config --get --bool revise.autoSquash` == `false`: false
if `git config --get --bool rebase.autoSquash` == `true`: true
otherwise: false

**Comment by lilyball** [comment]
Yes.
