### ISSUE TITLE
[Windows] editor round-trips through WSL

### ISSUE THREAD

**Issue by rainersigwald** [mystor/git-revise#19]
I have a Windows system with `GIT_EDITOR=code --wait`. When running `git revise -i {whatever}`, that editor is launched from within `bash`:

https://github.com/mystor/git-revise/blob/9f10441a9cfd989c562fc740dbf47b4edaebc284/gitrevise/utils.py#L58-L64

On Windows + recent copies of VS code, that invokes a fairly expensive operation that installs the [Visual Studio Code Remote - WSL](https://code.visualstudio.com/docs/remote/wsl) tools inside the WSL environment, then starts client and server processes to communicate with each other. Here, that's wasted effort amounting to several seconds of wait time, since the TODO file that's being edited is present on the Windows filesystem.

Is it possible to avoid the bash invocation, at least when running on Windows?

**Comment by mystor** [comment]
This was done to try to align with the way that git internally invokes the `GIT_EDITOR` command-line tool: https://github.com/git/git/blob/14c0f8d3ab6c36672189cd2dd217f4617d12ccba/git-sh-setup.sh#L151-L158

I'm guessing the reason for the slowness is because Git for Windows runs the bundled msys2 bash executable, while my script (incorrectly) runs whatever `bash` is on the path. I wonder how it would perform if I instead invoke `/bin/sh` or `sh`, to be more in-line with how git acts. I imagine that it'll behave poorly because `git-revise` is running as a windows python app, and not in the msys2 environment.

I'll have to think on this a bit, and perhaps look into how Git for Windows maintains its environment. There might be a way to ensure that we're running the command with the correct runtime environment by getting `git` to invoke the editor.

**Comment by leafgarland** [comment]
I'm suffering from a similar issue - the wsl bash doesn't see my Windows environment so I get a default editor instead of what I have set in `$GIT_EDITOR`.

Perhaps use Python to get the git editor instead of asking bash to do it, so that you avoid having to figure out which shell is the right one?

```py
editor = run(['git', 'var', 'GIT_EDITOR'], capture_output=True, text=True).stdout.strip()
run(
    [editor, path.name],
    check=True,
    cwd=path.parent,
)
```

**Comment by dgrunwald** [comment]
It's a bit more difficult than that -- for me `GIT_EDITOR` is set to `'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin`
That command doesn't work in the WSL bash (no `C:` there), but it also needs to parsed with bash-like logic (Windows cmd doesn't accept single quotes).

For me this did the trick:
```
        editor = run(['git', 'var', 'GIT_EDITOR'], capture_output=True, text=True).stdout
        run(
            shlex.split(editor, posix=True) + [path.name],
            check=True,
            cwd=path.parent,
        )
```
but it probably makes more sense to find and use the `bash` from the git for windows installation.

**Comment by mystor** [comment]
The separate run of `git var GIT_EDITOR` has been added in the (master-only) 162ce9593518a1d5c94b9928c7029cda40c274f3. 

I haven't figured out a great way to locate the git-for-windows `sh.exe` binary yet. I'm currently considering generating a `#!/bin/sh` file in the temporary directory, and running it as a git subcommand.

If anyone knows of a better way to locate the binary, please let me know!

**Comment by mystor** [comment]
I've added a workaround based on @dgrunwald's suggestion in 9a5bff26902c2229dd9b472fedb3545d412b15da. As I don't use Windows as my primary OS, it would be lovely if someone else who has encountered this issue could confirm if the `master` branch works for you.

**Comment by mystor** [comment]
I've filed #49 to follow-up on the remaining Windows editor compatibility issues, and will close this issue as we no longer round-trip through WSL.
