### ISSUE TITLE
Why not Golang or Rust?

### ISSUE THREAD

**Issue by kk-r** [mystor/git-revise#20]
I'm curious to know why we cant use Golang or Rust. :thinking:

**Comment by alerque** [comment]
I'm sure you _could_. Feel free to do a rewrite in Rust, I'd use it if it was otherwise on parity with this. A lot of the `git` itself has been getting such rewrites from shell scripts to compiled binaries and gaining performance along the way, but it takes a lot of time and effort ... in the mean time people use the skills they have. And I'm very thankful for this Python implementation, it has made my daily workflows faster already.

**Comment by kk-r** [comment]
@alerque Cool. Thanks for the great piece of work! :clap:
