### ISSUE TITLE
Fixup of fixup not detected correctly

### ISSUE THREAD

**Issue by Lameorc** [mystor/git-revise#58]
Hi, 
I often tend to do a lot of patches and then "squash" them at once. This also often means doing fixup commits to fixup commits. This seems to be completely fine with git rebase as it orders the commits correctly when using `--autosquash`. Revise on the other hand only moves the fist fixup commit, but not the subsequent one. I've done a minimal example in new repo, hope it helps with understanding the issue.

The git log after fixups
``` 
b87da89 (HEAD -> master) fixup! fixup! commit file
b6f2725 commit foo
30ef468 fixup! commit file
66129ee commit bar
8c62b80 commit file
```
What `git rebase -i --autosquash HEAD~5` shows:
```
pick 8c62b80 commit file
fixup 30ef468 fixup! commit file
fixup b87da89 fixup! fixup! commit file
pick 66129ee commit bar
pick b6f2725 commit foo
```
What `git revise -i --autosquash HEAD~5` shows:
```
pick 8c62b80f0846 commit file
fixup 30ef468dcb74 fixup! commit file
pick 66129ee8750d commit bar
fixup b87da89b57b3 fixup! fixup! commit file
pick b6f27254b70f commit foo
```

The revise command only reorders the first fixup, not the subsequent one.
My git version and git-revise version:
```
> git --version
git version 2.25.2
> git-revise --version
0.5.1
```

**Comment by mystor** [comment]
Thanks for the report!

This is likely caused by the fixup code iterating from latest commit back to oldest commit in the fixup range, rather than the other way around, when looking for `fixup!` commits, which causes it to find the double-fixup first.

This might be as simple as removing the `reversed` call in the `todo` code: https://github.com/mystor/git-revise/blob/dd50d19f793f304ec4e1261fdb81fc9d46397771/gitrevise/todo.py#L110
